/// One broad, built-in product group and the subcategories that belong to it.
///
/// Subcategory labels are not globally unique. Callers that need to identify a
/// path must retain both [name] and the selected subcategory.
final class CatalogCategoryGroup {
  const CatalogCategoryGroup({required this.name, required this.subcategories});

  final String name;
  final List<String> subcategories;
}

/// General-purpose offline taxonomy for a Philippine product catalog.
///
/// The hierarchy deliberately preserves repeated leaf labels under their
/// respective parents. For example, `Coffee & Tea` exists under both Food &
/// Beverages and Grocery & Daily Essentials.
const List<CatalogCategoryGroup> generalCatalogCategoryGroups = [
  CatalogCategoryGroup(
    name: 'Food & Beverages',
    subcategories: [
      'Fresh Food',
      'Meat & Poultry',
      'Seafood',
      'Fruits & Vegetables',
      'Bakery & Pastry',
      'Dairy & Eggs',
      'Snacks & Confectionery',
      'Canned & Preserved Food',
      'Frozen Food',
      'Rice, Grains & Cereals',
      'Noodles & Pasta',
      'Sauces & Condiments',
      'Cooking Ingredients',
      'Coffee & Tea',
      'Soft Drinks & Juices',
      'Water & Hydration',
      'Alcoholic Beverages',
      'Filipino Specialty Food',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Personal Care & Beauty',
    subcategories: [
      'Skincare',
      'Hair Care',
      'Bath & Body',
      'Oral Care',
      'Fragrance & Perfume',
      'Makeup & Cosmetics',
      "Men's Grooming",
      "Women's Care",
      'Shaving & Hair Removal',
      'Deodorants',
      'Nail Care',
      'Beauty Tools & Accessories',
      'Sun Care',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Health & Wellness',
    subcategories: [
      'Vitamins & Supplements',
      'First Aid',
      'Medical Supplies',
      'Personal Health Devices',
      'Pain Relief',
      'Digestive Health',
      'Immune Support',
      'Fitness Nutrition',
      'Mobility & Support',
      'Elderly Care',
      'Sexual Wellness',
      'Traditional & Herbal Products',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Household & Cleaning',
    subcategories: [
      'Laundry',
      'Dishwashing',
      'Kitchen Cleaning',
      'Bathroom Cleaning',
      'Floor & Surface Cleaning',
      'Disinfectants',
      'Air Fresheners',
      'Household Paper Products',
      'Trash & Waste Management',
      'Cleaning Tools',
      'Storage & Organization',
      'Pest Control',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Baby & Kids',
    subcategories: [
      'Baby Food',
      'Diapers',
      'Baby Bath & Care',
      'Baby Feeding',
      'Baby Clothing',
      'Baby Gear',
      'Strollers',
      'Car Seats',
      'Nursery',
      "Kids' Personal Care",
      "Kids' School Supplies",
      'Maternity & Pregnancy',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Clothing & Fashion',
    subcategories: [
      "Men's Clothing",
      "Women's Clothing",
      "Children's Clothing",
      'Baby Clothing',
      'Underwear & Lingerie',
      'Sleepwear',
      'Swimwear',
      'Activewear',
      'Traditional/Filipino Clothing',
      'Uniforms',
      'Jackets & Outerwear',
      'Plus Size',
      'Fashion Accessories',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Shoes & Accessories',
    subcategories: [
      "Men's Shoes",
      "Women's Shoes",
      "Kids' Shoes",
      'Sneakers',
      'Sandals',
      'Slippers',
      'Boots',
      'Work Shoes',
      'Bags & Backpacks',
      'Wallets & Card Holders',
      'Belts',
      'Hats & Caps',
      'Sunglasses',
      'Umbrellas',
      'Travel Accessories',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Electronics & Gadgets',
    subcategories: [
      'Smartphones',
      'Tablets',
      'Laptops & Computers',
      'Computer Accessories',
      'Mobile Accessories',
      'TVs & Displays',
      'Audio & Headphones',
      'Cameras',
      'Gaming',
      'Smart Devices',
      'Wearable Technology',
      'Networking',
      'Storage Devices',
      'Cables & Chargers',
      'Power Banks',
      'Electronic Components',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Home & Furniture',
    subcategories: [
      'Living Room Furniture',
      'Bedroom Furniture',
      'Dining Furniture',
      'Office Furniture',
      'Kitchen Furniture',
      'Outdoor Furniture',
      'Mattresses & Bedding',
      'Curtains & Blinds',
      'Home Decor',
      'Lighting & Lamps',
      'Rugs & Carpets',
      'Mirrors',
      'Kitchen & Dining',
      'Bathroom Accessories',
      'Storage Furniture',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Appliances',
    subcategories: [
      'Refrigerators & Freezers',
      'Washing Machines',
      'Dryers',
      'Air Conditioners',
      'Fans',
      'Ovens & Ranges',
      'Microwaves',
      'Rice Cookers',
      'Coffee Makers',
      'Blenders & Mixers',
      'Water Heaters',
      'Water Dispensers',
      'Vacuum Cleaners',
      'Air Purifiers',
      'Small Kitchen Appliances',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Sports & Fitness',
    subcategories: [
      'Fitness Equipment',
      'Gym Equipment',
      'Running',
      'Cycling',
      'Basketball',
      'Volleyball',
      'Football',
      'Boxing & Martial Arts',
      'Swimming',
      'Tennis',
      'Badminton',
      'Outdoor Recreation',
      'Camping',
      'Hiking',
      'Sportswear',
      'Sports Accessories',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Automotive',
    subcategories: [
      'Car Parts',
      'Motorcycle Parts',
      'Tires & Wheels',
      'Batteries',
      'Engine & Mechanical',
      'Car Electronics',
      'Motorcycle Accessories',
      'Car Interior Accessories',
      'Exterior Accessories',
      'Car Care & Cleaning',
      'Lubricants & Fluids',
      'Tools & Equipment',
      'Safety & Emergency',
      'Helmets & Riding Gear',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Tools & Hardware',
    subcategories: [
      'Hand Tools',
      'Power Tools',
      'Electrical Tools',
      'Plumbing',
      'Electrical Supplies',
      'Fasteners',
      'Building Materials',
      'Paint & Supplies',
      'Welding',
      'Safety Equipment',
      'Measuring Tools',
      'Hardware Accessories',
      'Industrial Equipment',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Pet Supplies',
    subcategories: [
      'Dog Supplies',
      'Cat Supplies',
      'Bird Supplies',
      'Fish & Aquarium',
      'Small Animals',
      'Pet Food',
      'Treats',
      'Pet Grooming',
      'Pet Health',
      'Pet Toys',
      'Pet Beds & Furniture',
      'Leashes & Collars',
      'Pet Travel Accessories',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Office & School Supplies',
    subcategories: [
      'Writing Instruments',
      'Paper Products',
      'Notebooks & Journals',
      'School Supplies',
      'Office Supplies',
      'Filing & Organization',
      'Printing Supplies',
      'Computer Accessories',
      'Art Supplies',
      'Craft Supplies',
      'Presentation Supplies',
      'Office Furniture',
      'Educational Materials',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Toys & Hobbies',
    subcategories: [
      'Action Figures',
      'Dolls',
      'Building Toys',
      'Educational Toys',
      'Board Games',
      'Card Games',
      'Puzzles',
      'Remote-Controlled Toys',
      'Outdoor Toys',
      'Pretend Play',
      'Collectibles',
      'Arts & Crafts',
      'Musical Toys',
      'Model Kits',
      'Hobby Equipment',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Books & Media',
    subcategories: [
      'Fiction',
      'Non-Fiction',
      "Children's Books",
      'Educational Books',
      'Textbooks',
      'Business & Finance',
      'Self-Help',
      'Religion & Spirituality',
      'Comics & Manga',
      'Magazines',
      'Newspapers',
      'Music',
      'Movies',
      'Digital Media',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Jewelry & Watches',
    subcategories: [
      'Fine Jewelry',
      'Fashion Jewelry',
      'Rings',
      'Necklaces',
      'Bracelets',
      'Earrings',
      'Watches',
      'Smartwatches',
      "Men's Jewelry",
      "Women's Jewelry",
      "Children's Jewelry",
      'Jewelry Accessories',
      'Jewelry Storage & Care',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Grocery & Daily Essentials',
    subcategories: [
      'Rice',
      'Cooking Oil',
      'Sugar & Sweeteners',
      'Salt & Seasonings',
      'Canned Goods',
      'Instant Food',
      'Coffee & Tea',
      'Beverages',
      'Snacks',
      'Breakfast Food',
      'Household Essentials',
      'Personal Hygiene',
      'Baby Essentials',
      'Frozen Products',
      'Pet Essentials',
    ],
  ),
  CatalogCategoryGroup(
    name: 'Agriculture & Garden',
    subcategories: [
      'Seeds',
      'Fertilizers',
      'Soil & Growing Media',
      'Gardening Tools',
      'Plant Pots & Containers',
      'Irrigation',
      'Pest Control',
      'Farm Equipment',
      'Agricultural Machinery',
      'Livestock Supplies',
      'Poultry Supplies',
      'Aquaculture',
      'Greenhouse Supplies',
      'Outdoor Plants',
      'Indoor Plants',
      'Garden Decor',
    ],
  ),
];

/// The 20 parent labels, in the order used by the built-in taxonomy.
final List<String> generalCatalogCategoryNames = List<String>.unmodifiable(
  generalCatalogCategoryGroups.map((group) => group.name),
);

/// All 283 parent-scoped entries, including repeated labels across parents.
final List<String> generalCatalogSubcategories = List<String>.unmodifiable(
  generalCatalogCategoryGroups.expand((group) => group.subcategories),
);
